---
- hosts: all
  tasks:
    - name: install git
      apt: name=git state=latest

    - name: install package software-properties-common, a ansible requirement
      apt: name=software-properties-common state=latest

    - name: add ansible package repository
      apt_repository: repo='ppa:ansible/ansible'
    
    - name: update package cache
      apt: update_cache=yes

    - name: install ansible
      apt: name=ansible state=latest

    # Install & Configure Spotify

    - name: Download Spotify required libgcrypt11 library
      get_url: url='http://security.ubuntu.com/ubuntu/pool/main/libg/libgcrypt11/libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb' dest='/tmp/libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb'
      sudo: true

    - name: Install libgcrypt11
      apt: deb='/tmp/libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb'

    - name: Add Spotify repository
      apt_repository: repo="deb http://repository.spotify.com stable non-free" state=present

    - name: Add Spotify public key
      apt_key: keyserver=keyserver.ubuntu.com id=D2C19886 state=present

    - name: Update package manager
      apt: update_cache=yes

    - name: Install latest spotify package
      apt: pkg="{{ item }}" state=latest force=yes
      with_items:
        - spotify-client
      
    # Create my user
    - name: Create my main user
      user: name=fabio password=$6$1U7Bd3AhPo$8.gb1qBMmJNVXJzqdvkNQP2pOrd6ZHCi5zp5yLScj8/rSF8rEfHBk9LQhAH.RyPx/YdZhXlutgX9o4daAXgDe. groups=adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare
    
