---
- hosts: all
  tasks:
    - name: install git
      apt: name=git state=latest

    - name: install package software-properties-common, a ansible requirement
      apt: name=software-properties-common state=latest

    - name: add ansible package repository
      apt_repository: repo='ppa:ansible/ansible' update_cache=yes

    - name: install ansible
      apt: name=ansible state=latest

    # Install & Configure Spotify

    - name: Download Spotify required libgcrypt11 library
      get_url: url='http://security.ubuntu.com/ubuntu/pool/main/libg/libgcrypt11/libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb' dest='/tmp/libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb'
      sudo: true

    - name: Install libgcrypt11
      apt: deb='/tmp/libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb'

    - name: Add Spotify public key
      apt_key: keyserver=keyserver.ubuntu.com id=D2C19886 state=present

    - name: Add Spotify repository
      apt_repository: repo="deb http://repository.spotify.com stable non-free" state=present update_cache=yes

    - name: Install latest spotify package
      apt: name=spotify-client state=latest
      
    # Create my user, to generate the crypted password, see http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
    - name: Create my main user
      user: name=fabio password=$6$1U7Bd3AhPo$8.gb1qBMmJNVXJzqdvkNQP2pOrd6ZHCi5zp5yLScj8/rSF8rEfHBk9LQhAH.RyPx/YdZhXlutgX9o4daAXgDe. groups=adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare
    
    # Install Skype
    - name: Add Canonical Partners repository
      apt_repository: repo='deb http://archive.canonical.com/ubuntu vivid partner' state=present update_cache=yes

    - name: Install Skype
      apt: name=skype state=latest

    # Install Google Chrome
    - name: Add Google signing key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub

    - name: Add Google repository
      apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present update_cache=yes

    - name: Add Google Chrome
      apt: name=google-chrome-stable state=latest


    # Install VirtualBox
    - name: Add VirtualBox repository public key
      apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc
      
    - name: Add VirtualBox repository
      apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian vivid contrib' state=present update_cache=yes

    - name: Add dkms package
      apt: name=dkms state=latest

    - name: Install VirtualBox
      apt: name=virtualbox-5.0 state=latest

    # Install Vagrant
    - name: Download Vagrant
      get_url: url='https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb' dest='/tmp/vagrant.deb'

    - name: Install Vagrant
      apt: deb='/tmp/vagrant.deb'

    # Install Packer
    - name: Create Applications directory
      file: path=/home/fabio/Applications/packer state=directory owner=fabio group=fabio mode=0755

    - name: Download Packer
      get_url: url='https://dl.bintray.com/mitchellh/packer/packer_0.8.6_linux_amd64.zip' dest='/tmp/packer.zip'

    - name: Unpack Packer
      unarchive: src=/tmp/packer.zip dest=/home/fabio/Applications/packer copy=no

    - name: Create bin directory
      file: path=/home/fabio/bin state=directory owner=fabio group=fabio mode=0755

    - name: Create symlinkto packer executable
      file: path=/home/fabio/bin/packer state=link src=/home/fabio/Applications/packer/packer
      
